### ISSUE TITLE
Data Dictionary Manager

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#34]
When a dictionary version is updated, data needs to be marked as valid or invalid. 

NOTE: this should be rolled out when we add new files.

- [ ] Management API
-- endpoints to migrate, test, and check 
-- endpoint to freeze uploads ?
- [ ] Detecting all breaking changes
-- listed in https://wiki.oicr.on.ca/display/icgcargotech/Submission+System+Technical+Architecture
-- stabilize the migration 
-- test plan on migration cases
- [ ] Reporting & Statistics on donor invalidation
-- record reason of invalidation
-- notification of invalidation 
- [ ] Managing active submissions 
-- add `invalid_migration` states somewhere
-- record which entity(s) have schema errors ; until the entities are replaced with valid data, then 
-- check needs for `upload` and `clear` to account for this 
--

**Comment by blabadi** [comment]
comments from demo today:
- block submissions while migration is ongoing
- migration status reporting to slack ?
- add tickets to cover the different possible breaking changes 
- add lastValidatedAgainstVersion in schemaMetadata  
- dry run enhancement to produce a more sophisticated report to communicate to projects
